[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
vault = "A7mCyk8eKwdkkTdFoF38aEs9GRqK7SCwaPGqzA1mzvr2"

[programs.devnet]
vault = "A7mCyk8eKwdkkTdFoF38aEs9GRqK7SCwaPGqzA1mzvr2"

[programs.testnet]
vault = "A7mCyk8eKwdkkTdFoF38aEs9GRqK7SCwaPGqzA1mzvr2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./Turbin3-wallet.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

